site_name: AfterBloom Wiki
site_author: ErrinDev
site_description: AfterBloom is a Minecraft network that focuses on the players.
site_url: https://wiki.AfterBloom.net
repo_name: AfterBloom Wiki
repo_url: https://github.com/AfterBloom-MC/wiki.AfterBloom.net

copyright: Copyright &copy; 2025 <a href="https://github.com/AfterBloom-MC" target="a_blank" rel"noopener">AfterBloom MC</a>

theme:
  name: material

  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  font:
    text: Open Sans
    code: Fira Code
  features:
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - announce.dismiss
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  language: en
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode
  icon:
    alternate: material/file-document-multiple-outline

extra:
  social:
    - icon: fontawesome/brands/discord
      class: md-social__link
      link: https://discord.gg/Afterbloom
      name: Discord
    - icon: fontawesome/brands/github
      class: md-social__link
      link: https://github.com/AfterBloom-MC
    - icon: fontawesome/solid/globe
      class: md-social__link
      link: https://www.afterbloom.net
      name: Website
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

nav:
  - AfterBloom:
    - Home: index.md
    - Getting started:
      - Important info: misc/important-info.md
      - Network Hub: servers/network-hub.md
      - Survival: servers/survival.md
      - Technical: servers/technical.md

  - Servers:
    - Network Hub: servers/network-hub.md
    - Survival: 
      - Technical: servers/technical.md
      - How to earn money: survival/how-to-earn-money.md
      - Fishing: survival/fishing.md

    
    

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true

watch:
  - includes